CREATE SCHEMA LUNATEST;

CREATE TABLE COUNTRY AS SELECT * FROM CSVREAD('src/main/resources/input-data/countries.csv');
CREATE TABLE AIRPORT AS SELECT * FROM CSVREAd('src/main/resources/input-data/airports.csv');
CREATE TABLE RUNWAY AS SELECT * FROM CSVREAD('src/main/resources/input-data/runways.csv');

CREATE INDEX IDX_COUNTRY_CODE ON COUNTRY(CODE);
CREATE INDEX IDX_COUNTRY_NAME ON COUNTRY(NAME);
CREATE INDEX IDX_AIRPORT_CODE ON AIRPORT(ISO_COUNTRY);
CREATE INDEX IDX_RUNWAY_AIRPORT ON RUNWAY(AIRPORT_REF);

CREATE VIEW VIEW_COUNTRY_MAX AS
	     SELECT COUNT (ID) AS AIR_COUNT, ISO_COUNTRY FROM AIRPORT GROUP BY ISO_COUNTRY;
	  

CREATE VIEW VIEW_SURFACE AS
	SELECT DISTINCT R.SURFACE, C.NAME FROM RUNWAY R 
		INNER JOIN AIRPORT A ON R.AIRPORT_REF = A.ID
		INNER JOIN COUNTRY C ON C.CODE = A.ISO_COUNTRY
	ORDER BY C.NAME, R.SURFACE
 
